---
title: "Sliding_Window"
author: "Sarah Arcos"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(weightedMI)

source("../Plot_Frequencies.R")
```

# Calculate MI for H3N2 polymerase using 5-year sliding windows

## Read in data

```{r}
seq_times <- readRDS("../data/seq_times_091122.rda")
pol <- readMSA("../../H3N2_Processing/pol_aa.fasta")
```

## Get start of each window

```{r}
start_years <- seq(min(seq_times$date), (max(seq_times$date) - 4))
```

## Define function to get sequences in each window

```{r}
get_window <- function(df, mat, start_year){
  window_df <- df %>%
    filter(date >= start_year & date < start_year+5)
  return(mat[window_df$rowname,])
}
```

## Calculate MI for each window

 - Uncomment code to actually run

```{r}
# window_results <- vector(mode = "list")
# 
# for (i in start_years){
#   window_results[[i]] <- get_window(seq_times, pol, i) %>%
#     calculateMI(ncores = 6)
#   print(paste("Done with window at", i))
# }
# 
# saveRDS(window_results, "../data/slidingWindows.rds")
```

## Plot MI of example residue pairs

 - For amino acid frequencies, use functions from Plot_Frequencies.R

```{r fig.width= 4}
window_results <- readRDS("../data/slidingWindows.rds")
windows <- data.table::rbindlist(window_results, idcol = TRUE)
mi_network_info <- readRDS("../data/mi_network_info.rds")

plot_example_mi <- function(v1, v2){
  
  window_example <- windows %>%
    filter(V1 == v1 & V2 == v2) %>%
    select(.id, Group, mi, mip, v1_entropy, v2_entropy) %>%
    full_join(tibble(.id = start_years), by = ".id") %>%
    complete(.id, Group, fill = list(mi = 0, mip = -Inf, v1_entropy = 0, v2_entropy = 0)) %>%
    filter(!is.na(Group)) %>%
    mutate(window_midpoint = .id + 2.5)
  
  ggplot(window_example, aes(x = window_midpoint, y = mi)) +
    geom_line() +
    scale_y_continuous(limits = c(0, 1),
                       breaks = c(0, 0.5, 1)) +
    theme_minimal() +
    labs(subtitle = "Mutual Information (5-year sliding window)",
         title = paste(get_index(v1), "and", get_index(v2)),
         x = "Date", y = "MI") +
    theme(text = element_text(size = 12))
}

plot_example_freqs(c(590, 1468))
# ggsave("../Figures/freqs_590_1468.pdf",
#        width = 3.8, height = 3)
plot_example_mi(590, 1468)
# ggsave("../Figures/mi_590_1468.pdf",
#        width = 2.5, height = 2)

plot_example_freqs(c(1228, 1866))
# ggsave("../Figures/freqs_1228_1866.pdf",
#        width = 3.8, height = 3)
plot_example_mi(1228, 1866)
# ggsave("../Figures/mi_1228_1866.pdf",
#        width = 2.5, height = 2)


```



